### ISSUE TITLE
I have used your code in my project, and want to make sure I'm in compliance.

### ISSUE THREAD

**Issue by johnsnook** [pimcore/search-query-parser#1]
Guten tag,  Herr Geat and Herr Moser.
First let me thank you for your exemplary work.  I found it very easy to understand and modify.
I took your code and heavily trimmed/changed it for my extension, [Yii2-parsel](https://github.com/johnsnook/yii2-parsel).  I have included a link to your repository in every license header and a copy of your license file.
I'm a bit stupid about licenses, so if there's any additions or changes you suggest, please don't hesitate in letting me know.

Thank you very much,
John Snook

**Comment by fashxp** [comment]
Thanks for your feedback and we are glad to hear that you can use the library!
As long as you have a reference to our library and your code has a GPL compatible license, everything is fine :)
